language: php
sudo: false

php:
  - 7.1
  - 7.2

before_script:
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then phpenv config-add ./tests/apc.ini; fi;
  - composer install

script:
  - composer test
  - composer cs-check
