language: php
sudo: false

php:
  - 7.1
  - 7.2
  - nightly

before_script:
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then phpenv config-add ./tests/apc.ini; fi;
  - composer install
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - composer test
  - composer cs-check

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
